name: Docker CI

on:
  push:
    tags:
      - "*"        # ทุก tag
      # หรือถ้าจะจำกัด prefix เช่น v1.0.0
      # - "v*"

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # ---------- Docker Login ----------
    - name: Debug Docker Hub variables
      run: |
        echo "DOCKERHUB_USERNAME=${{ vars.DOCKERHUB_USERNAME }}"

        if [ -z "${{ vars.DOCKERHUB_TOKEN }}" ]; then
          echo "DOCKERHUB_TOKEN is EMPTY"
        else
          echo "DOCKERHUB_TOKEN is SET (have value)"
        fi

    # ---------- Backend ----------
    - name: Build & Push Backend
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: tew56789/todo-backend:${{ github.ref_name }}

    # ---------- Frontend ----------
    - name: Build & Push Frontend
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: tew56789/todo-frontend:${{ github.ref_name }}
